import { defineConfig } from "sanity";
import { structureTool } from "sanity/structure";

export default defineConfig({
  name: "grehyni-narvaez",
  title: "Grehyni Narvaez Venezuela",
  projectId: "zgtjgkvi",
  dataset: "production",
  basePath: "/studio",
  plugins: [structureTool()],
  schema: {
    types: [
      {
        name: "property",
        title: "Propiedad",
        type: "document",
        fields: [
          {
            name: "slug",
            title: "URL Slug",
            type: "slug",
            options: { source: "titleEs" },
            validation: (Rule) => Rule.required(),
          },
          { name: "titleEs", title: "Nombre (Español)", type: "string", validation: (Rule) => Rule.required() },
          { name: "titleEn", title: "Name (English)", type: "string" },
          { name: "descriptionEs", title: "Descripción (Español)", type: "text", rows: 4 },
          { name: "descriptionEn", title: "Description (English)", type: "text", rows: 4 },
          {
            name: "type",
            title: "Tipo",
            type: "string",
            options: {
              list: [
                { title: "Apartamento", value: "apartment" },
                { title: "Casa", value: "house" },
                { title: "Comercial", value: "commercial" },
                { title: "Terreno", value: "land" },
              ],
            },
          },
          { name: "price", title: "Precio", type: "string", description: "Ej: \"$185,000\" o \"Consultar\"" },
          { name: "locationEs", title: "Ubicación (Español)", type: "string" },
          { name: "locationEn", title: "Location (English)", type: "string" },
          { name: "bedrooms", title: "Habitaciones", type: "number" },
          { name: "bathrooms", title: "Baños", type: "number" },
          { name: "area", title: "Área (m²)", type: "string" },
          {
            name: "images",
            title: "Imágenes",
            type: "array",
            of: [{ type: "image", options: { hotspot: true } }],
          },
          { name: "featuresEs", title: "Características (Español)", type: "array", of: [{ type: "string" }] },
          { name: "featuresEn", title: "Features (English)", type: "array", of: [{ type: "string" }] },
          { name: "featured", title: "Destacada (mostrar en inicio)", type: "boolean" },
          { name: "developer", title: "Desarrollador", type: "string" },
          { name: "website", title: "Website del Proyecto", type: "url" },
          { name: "brochure", title: "Brochure PDF", type: "file" },
        ],
      },
      {
        name: "testimonial",
        title: "Testimonio",
        type: "document",
        fields: [
          { name: "name", title: "Nombre del Cliente", type: "string", validation: (Rule) => Rule.required() },
          { name: "locationEs", title: "Ubicación (Español)", type: "string" },
          { name: "locationEn", title: "Location (English)", type: "string" },
          { name: "textEs", title: "Testimonio (Español)", type: "text" },
          { name: "textEn", title: "Testimonial (English)", type: "text" },
        ],
      },
      {
        name: "instagramPost",
        title: "Post de Instagram",
        type: "document",
        fields: [
          {
            name: "url",
            title: "URL del Post de Instagram",
            type: "url",
            description: "Pega la URL completa (ej: https://www.instagram.com/p/ABC123/)",
            validation: (Rule) => Rule.required(),
          },
          { name: "titleEs", title: "Título (Español)", type: "string" },
          { name: "titleEn", title: "Title (English)", type: "string" },
          { name: "descriptionEs", title: "Descripción corta (Español)", type: "text", rows: 2 },
          { name: "descriptionEn", title: "Short description (English)", type: "text", rows: 2 },
          { name: "thumbnail", title: "Imagen de Portada", type: "image", options: { hotspot: true } },
        ],
      },
      {
        name: "siteSettings",
        title: "Configuración del Sitio",
        type: "document",
        fields: [
          { name: "heroTitle", title: "Título del Hero (Español)", type: "string" },
          { name: "heroTitleEn", title: "Hero Title (English)", type: "string" },
          { name: "heroSubtitle", title: "Subtítulo (Español)", type: "string" },
          { name: "heroSubtitleEn", title: "Subtitle (English)", type: "string" },
          { name: "phone", title: "Teléfono / WhatsApp", type: "string" },
          { name: "email", title: "Email", type: "string" },
          { name: "instagram", title: "Instagram URL", type: "url" },
          { name: "facebook", title: "Facebook URL", type: "url" },
          { name: "youtube", title: "YouTube URL", type: "url" },
        ],
      },
    ],
  },
});
